language: android
jdk: oraclejdk7
cache: false
sudo: true

env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_TARGET=android-23
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-android-$ANDROID_API_LEVEL

before_script:
  # Grant execution permissions
  - chmod +x gradlew
  - chmod +x wait_for_emulator

  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-boot-anim -no-audio -no-window &

script:
  - ./wait_for_emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex
